### ISSUE TITLE
Where to download the 3ds max plugin library?

### ISSUE THREAD

**Issue by Leadwerks** [EricLengyel/OpenGEX#4]
I've been searching everywhere for this, but its location is a mystery.

**Comment by EricLengyel** [comment]
The source code is in the [Exporter3dsmax](https://github.com/EricLengyel/OpenGEX/tree/main/Exporter3dsmax) folder. Do you mean a pre-built version?

**Comment by Leadwerks** [comment]
It looks like this requires a library from some 3ds max plugin SDK? It includes files like "maxapi.h", etc. Try as I might, I can't find where to download this library from Discrete.

**Comment by EricLengyel** [comment]
Here's the page where you can download the SDK:

https://www.autodesk.com/developer-network/platform-technologies/3ds-max

You need to use the version that corresponds to the version of 3ds max installed, which is why a pre-built binary is not supplied here.

**Comment by Leadwerks** [comment]
Thanks. :) I was on that page previously, but I kept going to Github instead of scrolling down further.
